import networks from "../data/networks.list.ts";
import { NetworkMap, ChainMap } from "../data/types";
import { getWorkingRPCs } from "./utils";

/** Returns a network map containing only working network RPCs */
const getWorkingNetworks = async (networks: NetworkMap) => {
  const workingNetworks: NetworkMap = {};

  for (let [networkName, networkMap] of Object.entries(networks)) {
    const chains: ChainMap = {};

    console.log(`Checking RPCs for ${networkName}...`);
    for (let [chainName, chainInfo] of Object.entries(networkMap)) {
      chains[chainName] = {
        name: chainInfo.name,
        chainId: chainInfo.chainId,
        rpc: await getWorkingRPCs(chainInfo.rpc),
      };
    }

    workingNetworks[networkName] = chains;
  }

  return workingNetworks;
};

const generateSource = async (networks: NetworkMap) => {
  let files: Record<string, string> = {};

  // make a file for each network
  for (let [networkName, networkMap] of Object.entries(networks)) {
    let src = `// THIS FILE IS AUTOGENERATED\n// DO NOT EDIT\n\n`;
    src += `import { asProxyArray } from "./utils";\n`;

    for (let [chainName, chainInfo] of Object.entries(networkMap)) {
      src += `\n// ${chainInfo.name.toUpperCase()}\n`;
      src += `const ${chainName}RPCs = ${JSON.stringify(
        chainInfo.rpc,
        null,
        2
      )};\n`;
    }

    src += `export default {`;
    for (let [chainName, chainInfo] of Object.entries(networkMap)) {
      src += `\n  ${chainName}: asProxyArray<typeof ${chainName}RPCs, string>(${chainName}RPCs),`;
    }
    src += `\n}\n`;

    files[`${networkName}.ts`] = src;
  }

  // make chainid file
  let chainIdsSrc = `// THIS FILE IS AUTOGENERATED\n// DO NOT EDIT\n\n`;

  chainIdsSrc += `export default {\n`;
  for (let [networkName, networkMap] of Object.entries(networks)) {
    for (let [chainName, chainInfo] of Object.entries(networkMap)) {
      chainIdsSrc += `  ${chainInfo.chainId}: { network: "${networkName}", chain: "${chainName}" },\n`;
    }
  }
  chainIdsSrc += `}\n`;
  files["chainIds.ts"] = chainIdsSrc;

  // make the index file
  let indexSrc = `// THIS FILE IS AUTOGENERATED\n// DO NOT EDIT\n\n`;
  indexSrc += `import { asProxyWithChainId } from "./utils";\n`;
  indexSrc += `import chainIds from "./chainIds";\n`;

  for (let [networkName, networkMap] of Object.entries(networks)) {
    indexSrc += `\nimport ${networkName} from "./${networkName}";`;
  }

  indexSrc += `\n\nexport default asProxyWithChainId({`;
  for (let [networkName, networkMap] of Object.entries(networks)) {
    indexSrc += `\n  ${networkName},`;
  }
  indexSrc += `\n}, chainIds);\n`;

  files["index.ts"] = indexSrc;
  return files;
};

const main = async () => {
  const workingNetworks = await getWorkingNetworks(networks);
  const files = await generateSource(workingNetworks);

  for (let [filename, src] of Object.entries(files)) {
    const filepath = `./src/${filename}`;
    await Bun.write(filepath, src);
    console.log(`Wrote ${filepath} ✔️`);
  }
};

main()
  .then(() => console.log("Done!"))
  .catch((e) => console.error(e))
  .finally(() => process.exit(0));
