// THIS FILE IS AUTOGENERATED
// DO NOT EDIT

import { asProxyArray } from "./utils";

// ARBITRUM MAINNET
const mainnetRPCs = {
  "Arbitrum": "https://arb1.arbitrum.io/rpc",
  "PublicNode": "https://arbitrum-one.publicnode.com",
  "LLamaNodes": "https://arbitrum.llamarpc.com",
  "Blast": "https://arbitrum-one.public.blastapi.io",
  "Meow": "https://arbitrum.meowrpc.com",
  "Ankr": "https://rpc.ankr.com/arbitrum"
};

// ARBITRUM GOERLI
const goerliRPCs = {
  "Arbitrum": "https://goerli-rollup.arbitrum.io/rpc",
  "PublicNode": "https://arbitrum-goerli.publicnode.com",
  "Blast": "https://arbitrum-goerli.public.blastapi.io"
};

// ARBITRUM SEPOLIA
const sepoliaRPCs = {
  "Arbitrum": "https://sepolia-rollup.arbitrum.io/rpc"
};

// ARBITRUM NOVA
const novaRPCs = {
  "Arbitrum": "https://nova.arbitrum.io/rpc",
  "PublicNode": "https://arbitrum-nova.publicnode.com",
  "Blast": "https://arbitrum-nova.public.blastapi.io"
};
export default {
  mainnet: asProxyArray<typeof mainnetRPCs, string>(mainnetRPCs),
  goerli: asProxyArray<typeof goerliRPCs, string>(goerliRPCs),
  sepolia: asProxyArray<typeof sepoliaRPCs, string>(sepoliaRPCs),
  nova: asProxyArray<typeof novaRPCs, string>(novaRPCs),
}
