// THIS FILE IS AUTOGENERATED
// DO NOT EDIT


// ARBITRUM MAINNET
const mainnetInfo = {
  "chainId": 42161,
  "name": "Arbitrum Mainnet",
  "iconUrl": "https://raw.githubusercontent.com/CryptoKass/chainmap/main/assets/img/networks/arbitrum.svg",
  "currency": {
    "name": "Ethereum",
    "symbol": "ETH",
    "decimals": 18
  },
  "explorerUrl": "https://arbiscan.io",
  "rpc": [
    "https://arb1.arbitrum.io/rpc",
    "https://arbitrum-one.publicnode.com",
    "https://arbitrum.llamarpc.com",
    "https://arbitrum-one.public.blastapi.io",
    "https://arbitrum.meowrpc.com",
    "https://rpc.ankr.com/arbitrum"
  ]
} 

// ARBITRUM GOERLI
const goerliInfo = {
  "chainId": 421613,
  "name": "Arbitrum Goerli",
  "iconUrl": "https://raw.githubusercontent.com/CryptoKass/chainmap/main/assets/img/networks/arbitrum.svg",
  "currency": {
    "name": "Ethereum",
    "symbol": "ETH",
    "decimals": 18
  },
  "explorerUrl": "https://goerli.arbiscan.io",
  "rpc": [
    "https://goerli-rollup.arbitrum.io/rpc",
    "https://arbitrum-goerli.publicnode.com",
    "https://arbitrum-goerli.public.blastapi.io"
  ]
} 

// ARBITRUM SEPOLIA
const sepoliaInfo = {
  "chainId": 421614,
  "name": "Arbitrum Sepolia",
  "iconUrl": "https://raw.githubusercontent.com/CryptoKass/chainmap/main/assets/img/networks/arbitrum.png",
  "currency": {
    "name": "Ethereum",
    "symbol": "ETH",
    "decimals": 18
  },
  "explorerUrl": "https://sepolia.arbiscan.io",
  "rpc": [
    "https://sepolia-rollup.arbitrum.io/rpc"
  ]
} 

// ARBITRUM NOVA
const novaInfo = {
  "chainId": 42170,
  "name": "Arbitrum Nova",
  "currency": {
    "name": "Ethereum",
    "symbol": "ETH",
    "decimals": 18
  },
  "explorerUrl": "https://nova.arbiscan.io",
  "rpc": [
    "https://nova.arbitrum.io/rpc",
    "https://arbitrum-nova.publicnode.com",
    "https://arbitrum-nova.public.blastapi.io"
  ]
} 

export default {
  mainnet: mainnetInfo,
  goerli: goerliInfo,
  sepolia: sepoliaInfo,
  nova: novaInfo,
}
