// THIS FILE IS AUTOGENERATED
// DO NOT EDIT


// AURORA MAINNET
const mainnetInfo = {
  "chainId": 1313161554,
  "name": "Aurora Mainnet",
  "iconUrl": "https://raw.githubusercontent.com/CryptoKass/chainmap/main/assets/img/networks/aurora.svg",
  "currency": {
    "name": "Ethereum",
    "symbol": "ETH",
    "decimals": 18
  },
  "explorerUrl": "https://aurorascan.dev",
  "rpc": [
    "https://mainnet.aurora.dev",
    "https://aurora-mainnet.gateway.tatum.io",
    "https://1rpc.io/aurora"
  ]
} 

// AURORA TESTNET
const testnetInfo = {
  "chainId": 1313161555,
  "name": "Aurora Testnet",
  "iconUrl": "https://raw.githubusercontent.com/CryptoKass/chainmap/main/assets/img/networks/aurora.svg",
  "currency": {
    "name": "Ethereum",
    "symbol": "ETH",
    "decimals": 18
  },
  "explorerUrl": "https://testnet.aurorascan.dev",
  "rpc": [
    "https://testnet.aurora.dev",
    "https://aurora-testnet.drpc.org"
  ]
} 

export default {
  mainnet: mainnetInfo,
  testnet: testnetInfo,
}
