// THIS FILE IS AUTOGENERATED
// DO NOT EDIT


// AVALANCHE C-CHAIN
const mainnetInfo = {
  "explorerUrl": "https://snowtrace.io",
  "chainId": 43114,
  "name": "Avalanche C-chain",
  "iconUrl": "https://raw.githubusercontent.com/CryptoKass/chainmap/main/assets/img/networks/avalanche.svg",
  "currency": {
    "name": "Avalanche",
    "symbol": "AVAX",
    "decimals": 18
  },
  "rpc": [
    "https://api.avax.network/ext/bc/C/rpc",
    "https://avalanche-c-chain.publicnode.com",
    "wss://avalanche-c-chain.publicnode.com"
  ],
  "infoUrl": "https://www.avax.network/",
  "faucets": []
} 

// AVALANCHE FUJI TESTNET
const testnetInfo = {
  "explorerUrl": "https://testnet.snowtrace.io",
  "chainId": 43113,
  "name": "Avalanche Fuji Testnet",
  "iconUrl": "https://raw.githubusercontent.com/CryptoKass/chainmap/main/assets/img/networks/avalanche.svg",
  "currency": {
    "name": "Avalanche",
    "symbol": "AVAX",
    "decimals": 18
  },
  "rpc": [
    "https://api.avax-test.network/ext/bc/C/rpc",
    "https://avalanche-fuji-c-chain.publicnode.com",
    "wss://avalanche-fuji-c-chain.publicnode.com"
  ],
  "infoUrl": "https://cchain.explorer.avax-test.network",
  "faucets": [
    "https://faucet.avax-test.network/"
  ]
} 

export default {
  mainnet: mainnetInfo,
  testnet: testnetInfo,
}
