// THIS FILE IS AUTOGENERATED
// DO NOT EDIT


// BASE
const mainnetInfo = {
  "explorerUrl": "https://basescan.org",
  "chainId": 8453,
  "name": "Base",
  "currency": {
    "name": "Ether",
    "symbol": "ETH",
    "decimals": 18
  },
  "rpc": [
    "https://mainnet.base.org/",
    "https://developer-access-mainnet.base.org/",
    "https://base.gateway.tenderly.co",
    "wss://base.gateway.tenderly.co",
    "https://base.publicnode.com",
    "wss://base.publicnode.com"
  ],
  "infoUrl": "https://base.org",
  "faucets": []
} 

export default {
  mainnet: mainnetInfo,
}
