// THIS FILE IS AUTOGENERATED
// DO NOT EDIT

export default {
  1: { network: "ethereum", chain: "mainnet" },
  5: { network: "ethereum", chain: "goerli" },
  11155111: { network: "ethereum", chain: "sepolia" },
  56: { network: "smartchain", chain: "mainnet" },
  97: { network: "smartchain", chain: "testnet" },
}
