// THIS FILE IS AUTOGENERATED
// DO NOT EDIT

export default {
  1: { network: "ethereum", chain: "mainnet" },
  5: { network: "ethereum", chain: "goerli" },
  11155111: { network: "ethereum", chain: "sepolia" },
  56: { network: "smartchain", chain: "mainnet" },
  97: { network: "smartchain", chain: "testnet" },
  42161: { network: "arbitrum", chain: "mainnet" },
  421613: { network: "arbitrum", chain: "goerli" },
  421614: { network: "arbitrum", chain: "sepolia" },
  42170: { network: "arbitrum", chain: "nova" },
  137: { network: "polygon", chain: "mainnet" },
  1101: { network: "polygon", chain: "zkevm" },
  80001: { network: "polygon", chain: "mumbai" },
  1442: { network: "polygon", chain: "zkevmtest" },
}
