// THIS FILE IS AUTOGENERATED
// DO NOT EDIT

export default {
  1: { network: "ethereum", chain: "mainnet" },
  5: { network: "ethereum", chain: "goerli" },
  11155111: { network: "ethereum", chain: "sepolia" },
};
