// THIS FILE IS AUTOGENERATED
// DO NOT EDIT


// CRONOS MAINNET
const mainnetInfo = {
  "chainId": 25,
  "name": "Cronos Mainnet",
  "currency": {
    "name": "CRO",
    "symbol": "CRO",
    "decimals": 18
  },
  "rpc": [
    "https://cronos-evm.publicnode.com",
    "https://evm.cronos.org",
    "https://cronos.blockpi.network/v1/rpc/public",
    "cronos.rpc.thirdweb.com"
  ],
  "explorerUrl": "https://cronoscan.com"
} 

export default {
  mainnet: mainnetInfo,
}
