// THIS FILE IS AUTOGENERATED
// DO NOT EDIT


// FANTOM OPERA
const mainnetInfo = {
  "explorerUrl": "https://ftmscan.com",
  "chainId": 250,
  "name": "Fantom Opera",
  "iconUrl": "https://raw.githubusercontent.com/CryptoKass/chainmap/main/assets/img/network/fantom.svg",
  "currency": {
    "name": "Fantom",
    "symbol": "FTM",
    "decimals": 18
  },
  "rpc": [
    "https://rpc.ftm.tools",
    "https://fantom.publicnode.com",
    "wss://fantom.publicnode.com"
  ],
  "infoUrl": "https://fantom.foundation",
  "faucets": []
} 

// FANTOM TESTNET
const testnetInfo = {
  "explorerUrl": "https://testnet.ftmscan.com",
  "chainId": 4002,
  "name": "Fantom Testnet",
  "iconUrl": "https://raw.githubusercontent.com/CryptoKass/chainmap/main/assets/img/network/fantom.svg",
  "currency": {
    "name": "Fantom",
    "symbol": "FTM",
    "decimals": 18
  },
  "rpc": [
    "https://rpc.testnet.fantom.network",
    "https://fantom-testnet.publicnode.com",
    "wss://fantom-testnet.publicnode.com"
  ],
  "infoUrl": "https://docs.fantom.foundation/quick-start/short-guide#fantom-testnet",
  "faucets": [
    "https://faucet.fantom.network"
  ]
} 

export default {
  mainnet: mainnetInfo,
  testnet: testnetInfo,
}
