// THIS FILE IS AUTOGENERATED
// DO NOT EDIT


// GNOSIS
const mainnetInfo = {
  "chainId": 100,
  "name": "Gnosis",
  "infoURL": "https://docs.gnosischain.com",
  "currency": {
    "name": "xDAI",
    "symbol": "XDAI",
    "decimals": 18
  },
  "explorerUrl": "https://gnosisscan.io",
  "rpc": [
    "https://rpc.gnosischain.com",
    "https://rpc.gnosis.gateway.fm",
    "https://rpc.ankr.com/gnosis",
    "https://gnosischain-rpc.gateway.pokt.network",
    "https://gnosis-mainnet.public.blastapi.io",
    "https://gnosis.api.onfinality.io/public",
    "https://gnosis.blockpi.network/v1/rpc/public",
    "https://web3endpoints.com/gnosischain-mainnet",
    "https://gnosis.oat.farm"
  ]
} 

export default {
  mainnet: mainnetInfo,
}
