// THIS FILE IS AUTOGENERATED
// DO NOT EDIT

import { asProxyWithChainId } from "./utils";
import chainIds from "./chainIds";

import ethereum from "./ethereum";
import smartchain from "./smartchain";

export default asProxyWithChainId({
  ethereum,
  smartchain,
}, chainIds);
