// THIS FILE IS AUTOGENERATED
// DO NOT EDIT

import { asProxyWithChainId } from "./utils";
import chainIds from "./chainIds";

// Supported Networks
import base from "./base";
import cronos from "./cronos";
import harmony from "./harmony";
import ethereum from "./ethereum";
import arbitrum from "./arbitrum";
import avalanche from "./avalanche";
import zora from "./zora";
import moonbeam from "./moonbeam";
import celo from "./celo";
import klayton from "./klayton";
import fantom from "./fantom";
import polygon from "./polygon";
import gnosis from "./gnosis";
import smartchain from "./smartchain";
import optimism from "./optimism";

export default asProxyWithChainId({
  base,
  cronos,
  harmony,
  ethereum,
  arbitrum,
  avalanche,
  zora,
  moonbeam,
  celo,
  klayton,
  fantom,
  polygon,
  gnosis,
  smartchain,
  optimism,
}, chainIds);
