// THIS FILE IS AUTOGENERATED
// DO NOT EDIT

import { asProxyWithChainId } from "./utils";
import chainIds from "./chainIds";

// Supported Networks
import gnosis from "./gnosis";
import harmony from "./harmony";
import zora from "./zora";
import celo from "./celo";
import klayton from "./klayton";
import avalanche from "./avalanche";
import ethereum from "./ethereum";
import optimism from "./optimism";
import polygon from "./polygon";
import base from "./base";
import moonbeam from "./moonbeam";
import fantom from "./fantom";
import arbitrum from "./arbitrum";
import smartchain from "./smartchain";
import cronos from "./cronos";

export default asProxyWithChainId({
  gnosis,
  harmony,
  zora,
  celo,
  klayton,
  avalanche,
  ethereum,
  optimism,
  polygon,
  base,
  moonbeam,
  fantom,
  arbitrum,
  smartchain,
  cronos,
}, chainIds);
