// THIS FILE IS AUTOGENERATED
// DO NOT EDIT


// KLAYTON MAINNET
const mainnetInfo = {
  "chainId": 8217,
  "name": "Klayton Mainnet",
  "iconUrl": "https://raw.githubusercontent.com/CryptoKass/chainmap/main/assets/img/network/klaytn.svg",
  "currency": {
    "name": "Klaytn",
    "symbol": "KLAY",
    "decimals": 18
  },
  "infoUrl": "https://klaytn.foundation",
  "explorerUrl": "https://scope.klaytn.com/",
  "rpc": [
    "https://public-en-cypress.klaytn.net",
    "https://archive-en.cypress.klaytn.net",
    "https://klaytn-mainnet-rpc.allthatnode.com:8551",
    "https://klaytn.blockpi.network/v1/rpc/public",
    "https://klaytn.api.onfinality.io/public"
  ]
} 

export default {
  mainnet: mainnetInfo,
}
