// THIS FILE IS AUTOGENERATED
// DO NOT EDIT


// MOONBEAM
const beamInfo = {
  "explorerUrl": "https://moonbeam.moonscan.io",
  "chainId": 1284,
  "name": "Moonbeam",
  "currency": {
    "name": "Glimmer",
    "symbol": "GLMR",
    "decimals": 18
  },
  "rpc": [
    "https://rpc.api.moonbeam.network",
    "wss://wss.api.moonbeam.network"
  ],
  "infoUrl": "https://moonbeam.network/networks/moonbeam/",
  "faucets": []
} 

// MOONRIVER
const riverInfo = {
  "explorerUrl": "https://moonriver.moonscan.io",
  "chainId": 1285,
  "name": "Moonriver",
  "currency": {
    "name": "Moonriver",
    "symbol": "MOVR",
    "decimals": 18
  },
  "rpc": [
    "https://rpc.api.moonriver.moonbeam.network",
    "wss://wss.api.moonriver.moonbeam.network"
  ],
  "infoUrl": "https://moonbeam.network/networks/moonriver/",
  "faucets": []
} 

// MOONBASE ALPHA
const testnetInfo = {
  "explorerUrl": "https://moonbase.moonscan.io",
  "chainId": 1287,
  "name": "Moonbase Alpha",
  "currency": {
    "name": "Dev",
    "symbol": "DEV",
    "decimals": 18
  },
  "rpc": [
    "https://rpc.api.moonbase.moonbeam.network",
    "wss://wss.api.moonbase.moonbeam.network"
  ],
  "infoUrl": "https://docs.moonbeam.network/networks/testnet/",
  "faucets": []
} 

// MOONROCK
const rockInfo = {
  "chainId": 1288,
  "name": "Moonrock",
  "currency": {
    "name": "Rocs",
    "symbol": "ROC",
    "decimals": 18
  },
  "rpc": [
    "https://rpc.api.moonrock.moonbeam.network",
    "wss://wss.api.moonrock.moonbeam.network"
  ],
  "infoUrl": "https://docs.moonbeam.network/learn/platform/networks/overview/",
  "faucets": []
} 

export default {
  beam: beamInfo,
  river: riverInfo,
  testnet: testnetInfo,
  rock: rockInfo,
}
