// THIS FILE IS AUTOGENERATED
// DO NOT EDIT


// OP MAINNET
const mainnetInfo = {
  "chainId": 10,
  "name": "OP Mainnet",
  "infoURL": "https://optimism.io",
  "iconUrl": "https://raw.githubusercontent.com/CryptoKass/chainmap/main/assets/img/network/optimism.svg",
  "currency": {
    "name": "Ethereum",
    "symbol": "ETH",
    "decimals": 18
  },
  "explorerUrl": "https://optimistic.etherscan.io",
  "rpc": [
    "https://mainnet.optimism.io",
    "https://optimism.publicnode.com",
    "wss://optimism.publicnode.com",
    "https://optimism.gateway.tenderly.co",
    "wss://optimism.gateway.tenderly.co"
  ]
} 

export default {
  mainnet: mainnetInfo,
}
