// THIS FILE IS AUTOGENERATED
// DO NOT EDIT


// ZKSYNC MAINNET
const mainnetInfo = {
  "chainId": 324,
  "name": "ZkSync Mainnet",
  "iconUrl": "https://raw.githubusercontent.com/CryptoKass/chainmap/main/assets/img/networks/zksync.svg",
  "currency": {
    "name": "Ethereum",
    "symbol": "ETH",
    "decimals": 18
  },
  "explorerUrl": "https://explorer.zksync.io",
  "rpc": [
    "https://mainnet.era.zksync.io",
    "https://zksync.drpc.org",
    "https://1rpc.io/zksync2-era",
    "https://zksync.meowrpc.com"
  ]
} 

export default {
  mainnet: mainnetInfo,
}
