// THIS FILE IS AUTOGENERATED
// DO NOT EDIT


// ZORA
const mainnetInfo = {
  "explorerUrl": "https://explorer.zora.energy",
  "chainId": 7777777,
  "name": "Zora",
  "currency": {
    "name": "Ether",
    "symbol": "ETH",
    "decimals": 18
  },
  "rpc": [
    "https://rpc.zora.energy/"
  ],
  "infoUrl": "https://zora.energy",
  "faucets": []
} 

export default {
  mainnet: mainnetInfo,
}
