name: "Build"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate
        run: bun run generate

      - name: Build
        run: bun run build

      - name: Version Bump
        run: bun run bump

      - name: Git push
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'cryptokass@users.noreply.github.com'
          git add .
          git commit -m "🧹 chore: generate & build"
          git push
