name: "Build"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate
        run: bun run generate

      - name: Build
        run: bun run build

      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate and build"
          push: false
